# -*- coding: utf-8 -*-
"""DA 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzlgeGW7lPF3HD8nH1irtjtip0HEMEsF
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('Pima.csv')

data.head(5) #########printing data

data.shape ##########how many features and rows

data.info()  ### info about dataset  2.2 Sumarraizing dataset for prediction

data['x1'].describe()  ###statistics similary of others

data.dtypes  ## datatypes

train=np.array(data.iloc[0:600])  ##2.1 Loading data into training and testing
test=np.array(data.iloc[600:768])

train.shape  ### traiinging data size

test.shape ### testing datasize

from sklearn.naive_bayes import GaussianNB   ####importing guassian model

model = GaussianNB()

model.fit(train[:,0:8], train[:,8])  ##2.3 training the data for prediction

predicted= model.predict(test[:,0:8])
print(test[:,8])
print(predicted)  ## predicted data

count=0            ###### calulating acuracy
for l in range(168):
    if(predicted[l]==test[l,8]):
        count=count+1

print(count)  ###### print no of correctly matched samples out of 168

############ Accuracy is


print(count/168)