# -*- coding: utf-8 -*-
"""DA 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A27US5VKSRHg54V8daINnECJN3ZHoS7m
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline

from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('store.csv')

data.head()   ######info about data

data.info()    ###### info about data

data.dtypes   ##### info about types

data['Duration'].describe()  #### statistics

data=data.drop('Start date',axis=1)
data=data.drop('End date',axis=1)
data=data.drop('Start station',axis=1)
data=data.drop('End station',axis=1)

data.head()                                    ########### label encoder
le = LabelEncoder()
le.fit(data['Member type'])
data['Member type'] = le.transform(data['Member type'])

le = LabelEncoder()
le.fit(data['Bike number'])
data['Bike number'] = le.transform(data['Bike number'])

data.head()

data.shape     ###### data.size

train=np.array(data.iloc[0:85000])   ### spitting into training and tetsign
test=np.array(data.iloc[85000:,])

train.shape,test.shape       ########  train and test

from sklearn.naive_bayes import GaussianNB   ##### guassinan
model=GaussianNB()

model.fit(train[:,0:4],train[:,4])
predicted=model.predict(test[:,0:4])

predicted.shape

count=0                 ### accuracy
for l in range(30597):  
    if(predicted[l]==test[l,4]):
        count=count+1

count

print(count/30597)